#!/bin/bash
# -*- ENCODING: UTF-8 -*-

comand () {
	    if [[ $(echo $permited|grep "${chatuser}") = "" ]]; then
		 if [[ $(cat ${CID}|grep "${chatuser}") = "" ]]; then
			 case ${comando[0]} in
				 /[Ii]d|/[Ii]D)myid_src &;;
				 /[Mm]enu|[Mm]enu|/[Ss]tart|[Ss]tart|[Cc]omensar|/[Cc]omensar)menu_src &;;
				 /[Aa]yuda|[Aa]yuda|[Hh]elp|/[Hh]elp)ayuda_src &;;
				 /[Dd]onar|[Dd]onar)donar &;;
				 /[Ii]mg|[Ii]mg)reply &;;
				 /[Pp]rice|[Pp]price|[Pp]rices|/[Pp]rices)prices_on &;;
				 /sendid)send_ID &;;
				 /chekid)send_ID &;;
				 /kfree) kads &;;
				 #/folteto)reply &;;
				 /[Uu]pfile|[Uu]pfile|[Uu]pfile|/[Uu]pfile)reply &;;
				 /[Tt]erm|[Tt]erm)call.terminos &;;
				 /[Cc]upon|[Cc]upon)reply &;;
				 /[Nn]otify|[Nn]otify)reply &;;
				 /[Rr]cupon|[Rr]cupon)call.cange.cuponC "${comando[1]}" &;;
				 /*|*)invalido_fun &;;
			 esac
			 if [[ ${message_reply_to_message_message_id[$id]} ]]; then
				case ${message_reply_to_message_text[$id]} in
					'/cupon')call.cange.cupon;;
					'/notify')call.notify.send;;
					'/hsjdhsdhjsgdf')Cat.BOTON;;
					#*)invalido_fun;;
				esac
			return
			fi
		 else
		 	if [[ ${message_text[$id]} || ${callback_query_data[$id]} ]]; then
			 case ${comando[0]} in
				 /[Mm]enu|[Mm]enu|/[Ss]tart|[Ss]tart|[Cc]omensar|/[Cc]omensar)menu_src &;;
				 /[Aa]yuda|[Aa]yuda|[Hh]elp|/[Hh]elp)ayuda_src &;;
				 /[Ii]d|/[Ii]D)myid_src &;;
				 /[Ii]nstal)link_src &;;
				 /[Kk]eygen)gerar_key &;;
				 /[Rr]estart)call.revoc &;;
				 /[Kk]ltm)gerar_keyLTM &;;
				 /[Bb]anIP|[Bb]anIP)reply &;;
				 /[Pp]rice|[Pp]price|[Pp]rices|/[Pp]rices)prices_on &;;
				 /[Dd]onar|[Dd]onar)donar &;;
				 /[Uu]pfile|[Uu]pfile|[Uu]pfile|/[Uu]pfile)reply & ;;
				 /[Aa]ddrev|/[Rr]emote|/folteto)reply &;;
				 /[Dd]omainA|[Dd]omainA|[Dd]omainNS|/[Dd]omainNS|/domainns|/domaina)reply &;;
				 /[Cc]cupon|[Cc]cupon)reply &;;
				 /[No]otify|[Nn]otify)reply &;;
				 /upfile)reply &;;
				 /*|*)invalido_fun &;;
			 esac
			fi
			if [[ ${message_reply_to_message_message_id[$id]} ]]; then
				case ${message_reply_to_message_text[$id]} in
					#'/domainA')call.domainA;;
					/[Dd]omainA|[Dd]omainA|/domaina)call.domainA;;
					'/remote')call.remote;;
					#'/domainNS')call.domainNS;;
					[Dd]omainNS|/[Dd]omainNS|/domainns)call.domainNS;;
					'/addrev')addID_reventa;;
					'/banIP')killIP_reply;;
					'/upfile')download_FAC;;
					'/folteto')dupdate2;;
					'/img')img_reply;;
					'/ccupon')call.CrearCuponNew ;;
					'/cfj')call.CrearCuponNew;;
					#'/cupon')call.cange.cupon ;;
					*)invalido_fun;;
				esac
			return
			fi
			sleep .1
		 fi
	    else
	    	if [[ ${message_reply_to_message_message_id[$id]} ]]; then
				case ${message_reply_to_message_text[$id]} in
					'/del')deleteID_reply;;
					'/chat')call.msgENV;;
					'/remote')call.remote;;
					'/domainA')call.domainA;;
					'/domainNS')call.domainNS;;
					'/add')addID_reply;;
					'/addrev')addID_reventa;;
					'/buscar')searchID_reply;;
					'/banID')call.banID;;
					'/Uban')call.UbanID;;
					'/banIP')killIP_reply;;
					'/upfile')download_FAC;;
					'/folteto')dupdate2;;
					'/img')img_reply;;
					'/CPrecios')call.cambio_precios;;
					'/ccupon')call.CrearCuponNew;;
					'/cfj')call.CrearCuponNew;;
					'/notify')call.notify.send;;
					*)invalido_fun;;
				esac

			elif [[ ${message_document_file_id[$id]} ]]; then
					 download_file

	    	elif [[ ${message_text[$id]} || ${callback_query_data[$id]} ]]; then

		 		case ${comando[0]} in
					 /[Mm]enu|[Mm]enu|/[Ss]tart|[Ss]tart|[Cc]omensar|/[Cc]omensar)menu_src &;;
					 /[Dd]omainA|[Dd]omainA|[Dd]omainNS|/[Dd]omainNS|/domainns|/domaina)reply &;;
					 /[Aa]yuda|[Aa]yuda|[Hh]elp|/[Hh]elp)ayuda_src &;;
					 /[Ii]d|/[Ii]D)myid_src &;;
					 /[Kk]illid|[Kk]illid) dropID &;;
					 #/[Cc]hat|[Ch]hat)msj_chat &;;
					 /[Cc]hat|[Ch]hat)reply &;;
					 /[Ii]mg|[Ii]mg)reply &;;
					 /[Aa]dd|/[Dd]el)reply &;;
					 /upfile)reply &;;
					 /banID)reply &;;
					 /Uban)reply &;;
					 /[Rr]estart)call.revoc &;;
					 /[Aa]ddrev|/[Rr]emote|/folteto)reply &;;
					 /[Bb]uscar|[Bb]uscar)reply &;;
					 /[Bb]anIP|[Bb]anIP)reply &;;
					 /[Cc]atip|[Cc]atip)list_IP &;;
					 /[Pp]ower)start_gen &;;
					 /[Kk]eygen)gerar_key &;;
					 /[Kk]eyplus)gerar_plus &;;
					 /[Kk]ltm)gerar_keyLTM &;;
			 		 /[Ii]nfosys)infosys_src &;;
			 		 /[Ll]ist)listID_src &;;
			 		 /[Ii]dgen|[Ii]dgen)listID_GEN &;;
					 /[Rr]eboot)reboot_src &;;
			 		 /[Ii]nstal)link_src &;;
			 		 /[Cc]ache)cache_src &;;
					 /[Uu]pdate|/[Aa]ctualizar)update &;;
					 /[Dd]onar|[Dd]onar)donar_OnOff &;;
					 /[Pp]rice|[Pp]price|[Pp]rices|/[Pp]rices)prices_on &;;
					 /[Uu]pfile|[Uu]pfile|[Uu]pfile|/[Uu]pfile)reply & ;;
					 /[Cc]Precios)reply & ;;
					 /[Cc]upon|/[Cc]cupon)reply & ;;
					 /aggBT) addID_reply &;;
					 /kfree) kads &;;
					 /[Nn]otify|[Nn]otify)reply &;;
					 /kid) _killID &;;
			 		 /*|*)invalido_fun &;;
				esac

			fi

	    fi
}
