#!/bin/bash
[[ -d /root/RegBOT ]] || mkdir /root/RegBOT
#send_ID(){
#Call.BT.ADM "${chatuser}"
#}


send_ID() {
local id_solicitante=${chatuser}
MSG_id=$((${message_message_id} + 1 ))
[[ -z ${callback_query_from_first_name} ]] && firsnme="${message_from_first_name}" || firsnme="${callback_query_from_first_name}"
[[ -z ${callback_query_from_last_name} ]] && lastnme="${message_from_last_name}" || lastnme="${callback_query_from_last_name}"
[[ -z ${callback_query_from_username} ]] && nUSER=${message_from_username} || nUSER=${callback_query_from_username}
[[ -e /root/RegBOT/U_check.txt ]] && n_soli=$(cat /root/RegBOT/U_check.txt | grep ${chatuser} | wc -l) || n_soli=1
[[ $n_soli < 3 ]] && {
echo "${id_solicitante}" >> /root/RegBOT/U_check.txt
		  #bot_retor=" ✵$(call.barras '═' '31')✵ \n"
		  bot_retor=" ─── · · · ──── ꒰ ꒱ ──── · · · ─── \n"
          bot_retor+=" ❒  ${firsnme} ${lastnme} ❒\n"
		  [[ -z ${nUSER} ]] && bot_retor+=" ⚠️ USUARIO SIN ALIAS SOLICITO $(cat < /root/RegBOT/U_check.txt | wc -l) VECES ⚠️\n" || bot_retor+=" <u> UserName </u>: @${nUSER} SOLICITO $(($n_soli + 1)) VECES\n"
		  bot_retor+=" SOLICITUD N° $(cat < /root/RegBOT/U_check.txt | wc -l) RECIVIDA A LAS $(date +%R) ✅\n"
		  bot_retor+=" $(call.barras '═' '33') \n"
          bot_retor+=" VERIFIQUE SU INFORMACION ANTES DE APROBAR\n"
          bot_retor+=" ─── · · · ──── ꒰ ꒱ ──── · · · ─── \n"
          #bot_retor+=" $(call.barras '═' '33') \n"
		  call.ITEM.fijos "$(cat < ${CIDdir}/Admin-ID)" "${bot_retor}" "${id_solicitante}"
		  #msj_add "$(cat < ${CIDdir}/Admin-ID)" #----------------------------------AQUIIIIII
		  #--reply_markup "$(ShellBot.InlineKeyboardMarkup -b 'item_access')"
		  #[[ -z ${callback_query_data} ]] && codigo=$(echo ${message_text[$id]} | cut -d ' ' -f2) || codigo=$(echo ${callback_query_data} | cut -d ' ' -f2)
		  #msj_add "${1}"
    	bot_retorno="▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬ \n"
        bot_retorno+=" 🔰 𝚂𝚞 𝙸𝙳 【 <code>${id_solicitante}</code> 】 🔰\n"
        bot_retorno+="▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬ \n"
        [[ -z ${nUSER} ]] && bot_retorno+=" ⚠️ AÑADA UN ALIAS PARA PODER SOLICITAR ⚠️\n" || bot_retorno+=" UD SOLICITO AUTORIZACION A $(cat < /etc/ADM-db/resell)\n"
        [[ -z ${nUSER} ]] && bot_retorno+="   IMPOSIBLE VERIFICAR ID SIN ALIAS\n  REMARCA SU $(($n_soli + 1)) SOLITUD INVALIDA \n" || bot_retorno+=" ESTA ES SU $(($n_soli + 1)) SOLICITUD MEDIANTE ID DE REGISTRO\n"
        bot_retorno+="▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬ \n"
        [[ -z ${nUSER} ]] && bot_retorno+=" ⚠ ID ENVIADO CON ADVERTENCIA (POSIBLE BANEO DE ID) ⚠️\n" || bot_retorno+="      ✅ SOLICITUD N° $(cat < /root/RegBOT/U_check.txt | wc -l) REGISTRADA ✅\n"
        bot_retorno+="▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬ \n"
		bot_retorno+="   ❒ SOLICITUD FUE ENVIADA EXITOSAMENTE	✅\n"
        bot_retorno+="   ❒ NO NECECISA QUE VUELVA A SOLICITAR	♻️\n"
        bot_retorno+="   ❒ PODRAS GENERAR SUBDOMINIOS 999+		♻️\n"
        bot_retorno+="   ❒ EVITE BANEO DE SU ID 				🪬\n"
        bot_retorno+="   ❒ CANJEA TU CUPON CON /cupon \n"
        bot_retorno+="   ❒ SE ADMITEN MAXIMO 3 SOLICITUDES \n"
		bot_retorno+="   ❒ REVISA PRECIOS Y COSTOS 👉<a href='https://shoppy.gg/@ChumoGH/'>AQUI</a>👈 \n"
        bot_retorno+="▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬ \n"
		bot_retorno+=" ENVIE SU COPIA/CAPTURA/CORREO DE PAGO PARA SU AUTORIZACION\n"
		bot_retorno+="▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬ \n"
		msj_fun
			} || {
				bot_retorno="▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬ \n"
				bot_retorno+=" 🔰 𝚂𝚞 𝙸𝙳 【 <code>${id_solicitante}</code> 】 🔰\n"
				bot_retorno+="▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬ \n"
				[[ -z ${nUSER} ]] && bot_retorno+=" ⚠️ USUARIO SIN ALIAS ⚠️\n" || bot_retorno+=" <u> ALIAS</u>: @${nUSER} CON ID : <code>${id_solicitante}</code>\n"
				[[ -z ${nUSER} ]] && bot_retorno+=" ⚠️ AÑADA UN ALIAS PARA VALIDAR SU ${n_soli} SOLICITUD ⚠️\n" || bot_retorno+=" UD ENVIO ${n_soli} SOLICITUDES A $(cat < /etc/ADM-db/resell)\n"
				bot_retorno+="▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬ \n"
				[[ -z ${nUSER} ]] && bot_retorno+="   IMPOSIBLE VERIFICAR ID SIN ALIAS\n  REMARCA SU $(($n_soli + 1)) SOLITUD INVALIDA \n" || bot_retorno+="   ❒ EL BOT OMITIO TODAS SUS SOLICITUDES\n"
				bot_retorno+="   ❒ YA NO PODRA REALIZAR SOLICITUDES\n"
				bot_retorno+="   ❒ CONTACTE DIRECTAMENTE AL ADMINISTRADOR \n"
				bot_retorno+="   ❒ SOLICITIO 3 VECES SIN APROBACION \n"
				bot_retorno+="   ❒ DESBANEOS SOLO ADQUIRIENDO ACCESO!! \n"
				bot_retorno+="   ❒ REVISA PRECIOS Y COSTOS 👉<a href='https://shoppy.gg/@ChumoGH/'>AQUI</a>👈 \n"
				bot_retorno+="▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬ \n"
				bot_retorno+="     🚫🚫️ SU ID FUE BANEADO 🚫🚫 \n"
				bot_retorno+="▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬ \n"
				echo "${id_solicitante} | $(date '+%C%y-%m-%d')-$(date +%R)" >> /root/RegBOT/banID
			bot_retorno+="     💥 Bot ADMcgh GEN de KEY 💥\n"
			bot_retorno+="           ⚜ by @ChumoGH ⚜\n"
		bot_retorno+="▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬ \n"
		msj_fun
	}
}


call.banID(){
idBAN=$(echo ${message_text[$id]} | awk '{print $1}' | sed -e 's/[^a-z0-9 -]//ig')
idMSS=$(echo ${message_text[$id]} | awk '{print $3}')
echo "${idBAN} | ${idMSS} | $(date '+%C%y-%m-%d')-$(date +%R)" >> /root/RegBOT/banID
          bot_retorno+="▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬ \n"
          bot_retorno+=" FECHA DE REGISTRO : $(date '+%C%y-%m-%d')|$(date +%R)\n"
          bot_retorno+="▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬ \n"
          bot_retorno+="  ✅ ID BANEADO EXITOSAMENTE ✅\n"
          bot_retorno+="▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬ \n"
          bot_retorno+="RAZON : ${idMSS}\n"
          bot_retorno+="▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬ \n"
          	bot_retorno+="     💥 Bot ADMcgh GEN de KEY 💥\n"
			bot_retorno+="           ⚜ by @ChumoGH ⚜\n"
		  msj_fun
}

call.UbanID () {
if sed -i "/${message_text[$id]}/d" /root/RegBOT/banID; then
bot_retorno="▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬ \n"
bot_retorno+="  ID DESBANEADO EXITOSAMENTE!\n"
bot_retorno+="  ID : ${message_text[$id]} \n"
bot_retorno+="▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬ \n"
else
bot_retorno="▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬ \n"
bot_retorno+="  ERROR AL ELIMINAR ID DE REGISTROS \n"
bot_retorno+="  POSIBLEMENTE ${message_text[$id]} NO EXISTA \n"
bot_retorno+="▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬ \n"
fi
msj_fun
}

myid_src () {
MSG_id=$((${message_message_id} + 1 ))
[[ -z ${callback_query_from_username} ]] && nUSER=${message_from_username} || nUSER=${callback_query_from_username}
[[ ! -z $(cat /etc/ADM-db/Admin-ID|grep "${chatuser}" ) ]] && { #ENTRA A VERIFICAR ADM
bot_retorno+=" ▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬ \n"
bot_retorno+=" HOLA @${nUSER} UD ES ADM \n"
bot_retorno+="▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬ \n"
bot_retorno+=" DIJITA MENU /menu   🔰\n"
bot_retorno+="\n"
bot_retorno+="▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬ \n"
bot_retorno+="     💥 Bot ADMcgh GEN de KEY 💥\n"
bot_retorno+="           ⚜ by @ChumoGH ⚜\n"
bot_retorno+="▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬ \n"
#bot_retorno+="<b>bold</b>, <strong> bold</strong> \n
#<i>italic</i>, <em>italic</em>\n"
bot_retorno+=" <code>BORRAREMOS ESTE PRE ${message_message_id} </code>\n"
bot_retorno+=" <code>BORRAREMOS ESTE CODE ${MSG_id} </code>\n"
msj_fun
sleep 5s
msj_del ${message_message_id}
msj_del ${MSG_id}
} || { # SINO ES ADM - CAMBIA A USUARIOS AUTORIZADOS
	[[ $(cat ${CID}|grep "${chatuser}" ) = "" ]] && { # ENTRA A VERIFCAR USUARIOS QUE NO EXISTEN
		bot_retorno="▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬ \n"
		[[ -z ${nUSER} ]] && bot_retorno+=" ⚠️ USUARIO SIN ALIAS ⚠️\n" || bot_retorno+="𝙃𝙤𝙡𝙖 【 @${nUSER} 】, SU ID NO ESTA AUTORIZADO\n"
		bot_retorno+="  ADQUIERE UNA MENBRESIA O DIJITA /prices \n"
		bot_retorno+=" VISITA LA TIENDA 🛒🛍️ PINCHANDO 👉<a href='https://shoppy.gg/@ChumoGH/'>AQUI</a>👈\n"
        bot_retorno+="▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬ \n"
        bot_retorno+="𝚂𝚞 𝙸𝙳 【 <code>${chatuser}</code> 】\n"
        bot_retorno+="▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬ \n"
        bot_retorno+="👇PINCHA 👇 EN EL BOTON PARA QUE $(cat < /etc/ADM-db/resell) TE AUTORICE!!\n"
        bot_retorno+="▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬ \n"
		menu_printSN
		sleep 5s
		msj_del ${message_message_id}
		msj_del ${MSG_id}
	} || { # ENTRA A  IDS YA REGISTRADOS
			bot_retorno+=" ▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬ \n"
			bot_retorno+=" HOLA @${nUSER} SU ID ESTA REGISTRADO \n"
			bot_retorno+="▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬ \n"
			bot_retorno+="    🆔 : <code>${chatuser}</code> 🔰\n"
			bot_retorno+=" FECHA DE CORTE : ⏳ $(cat /etc/ADM-db/User-ID | grep ${chatuser}| awk '{print $3}') | $(date +%R)\n"
			bot_retorno+="\n"
			bot_retorno+="▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬ \n"
				bot_retorno+="     💥 Bot ADMcgh GEN de KEY 💥\n"
				bot_retorno+="           ⚜ by @ChumoGH ⚜\n"
			bot_retorno+="▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬ \n"
			msj_fun
		}
						} # FIN VERIFICAR ADM
}

killIP_reply () {

[[ $(cat /var/www/html/ChumoGH/checkIP.log | grep -w "${message_text[$id]}") ]] && {
sed -i "/${message_text[$id]}/d" /var/www/html/ChumoGH/checkIP.log
bot_retorno="▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬ \n"
bot_retorno+="  IP ELIMINADA DE REGISTRO EXITOSAMENTE!\n"
bot_retorno+="  IP : ${message_text[$id]} \n"
bot_retorno+="▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬ \n"
} || {
bot_retorno="▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬ \n"
bot_retorno+="  ERROR AL ELIMINAR IP DE REGISTROS \n"
bot_retorno+="  POSIBLEMENTE ${message_text[$id]} NO EXISTA \n"
bot_retorno+="▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬ \n"
}
msj_fun
}

deleteID_reply () {
ids=$(echo ${message_text[$id]} |  cut -d '|' -f1 | sed -e 's/[^a-z0-9 -]//ig')
idc=$(echo ${message_text[$id]} |  cut -d '|' -f2 | sed -e 's/[^a-z0-9 -]//ig')
# ids=$(echo ${message_text[$id]} | awk '{print $1}' | sed -e 's/[^a-z0-9 -]//ig')
# idc=$(echo ${message_text[$id]} | awk '{print $3}' | sed -e 's/[^a-z0-9 -]//ig')
#sed -i "/${message_text[$id]}/d" ${CID}
[[ $(cat ${CID} | grep -w ${ids}) ]] && {
sed -i "/${ids}/d" ${CID}
bot_retorno="▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬ \n"
          bot_retorno+=" ID ELIMINADO EXITOSAMENTE!\n"
		  bot_retorno+="Fecha de Corte : $(date '+%C%y-%m-%d') - $(date +%R)  \n"
          bot_retorno+=" ID Eliminado: ${ids}\n"
          bot_retorno+="▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬ \n"
          bot_retor="  🎊 𝙱𝚒𝚎𝚗𝚟𝚎𝚗𝚒𝚍𝚘  Nuevamente 𝚊𝚕  𝙱𝚘𝚝𝙶𝚎𝚗  𝙲𝚑𝚞𝚖𝚘𝙶𝙷-𝙰𝙳𝙼  🎊\n"
          bot_retor+=" ESTIMADO USUARIO ${chat_username} TU MEMBRESIA FUE REMOVIDA\n"
          bot_retor+="SI QUIERES APELAR ESCRIBE A $(cat < /etc/ADM-db/resell)\n"
          bot_retor+="▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬ \n"
      msj_fun
      msj_add ${ids}
      #upfile_src
	  call.file2 "${CID}" " Respaldo con @${chat_username} \n ID : ${nombrevalue} \n FECHA $(date '+%C%y-%m-%d')"
	} || {
	
	bot_retorno="▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬ \n"
          bot_retorno+=" ID NO EXISTE \n"
          bot_retorno+=" ID Eliminado: ${ids}\n"
          bot_retorno+="▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬ \n"
      msj_fun
	}
}

img_reply () {
local file_id
          ShellBot.getFile --file_id ${message_document_file_id[$id]}
          ShellBot.downloadFile --file_path "${return[file_path]}" --dir "/root/"
		  [[ -e ${return[file_path]} ]] && mv ${return[file_path]} "/root/"
local bot_retorno="ID user botgen\n"
		bot_retorno+="▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬ \n"
		bot_retorno+=" FILE ${return[file_path]} \n"
		bot_retorno+=" ▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬ \n"
ID_img=${message_photo_file_unique_id}
          bot_retorno+=" CALCULANDO ID DE MENSAJES \n"
          bot_retorno+=" ID FILE PHOTO : ${message_photo_file_id}\n"
		  bot_retorno+="▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬ \n"
          bot_retorno+=" ID UNICO FILE PHOTO : ${message_photo_file_unique_id}\n"
          bot_retorno+=" CAPTION : ${message_caption}\n"
          bot_retorno+="▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬ \n"
      msj_fun
      #upfile_src
	  msj_img "${ID_img}"
}

searchID_reply () {
searchID=$(cat -n /etc/ADM-db/User-ID | grep "${message_text[$id]}")
bot_retorno="▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬ \n"
        bot_retorno+=" MOSTRANDO RESULTADOS DE BUSQUEDA!\n"
		bot_retorno+=" ▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬ \n"
		[[ ! -z ${searchID} ]] && bot_retorno+=" N°${searchID} \n" || bot_retorno+=" ID NO ENCONTRADO \n"
      msj_fun
}

addID_reply () {
[[ -z ${callback_query_message_chat_id} ]] && delete_mss=${return[message_id]} || delete_mss=${callback_query_message_chat_id}
mensajeID="${return[message_id]}"
chatID="${return[chat_id]}"
#ShellBot.deleteMessage  --chat_id ${return[chat_id]} --message_id "${delete_mss}"
[[ -z ${callback_query_data} ]] && ids=$(echo ${message_text[$id]} | cut -d '|' -f1 | sed -e 's/[^a-z0-9 -]//ig') || ids=$(echo ${callback_query_data} | cut -d '|' -f1 | cut -d ' ' -f2 | sed -e 's/[^0-9]//ig') 
[[ -z ${callback_query_data} ]] && idc=$(echo ${message_text[$id]} |  cut -d '|' -f2 | sed -e 's/[^a-z0-9 -]//ig') || idc=$(echo ${callback_query_data} |  cut -d '|' -f2 | sed -e 's/[^a-z0-9 -]//ig')
[[ -z ${callback_query_data} ]] && _tru=$(echo ${message_text[$id]} |  cut -d '|' -f3) || _tru=$(echo ${callback_query_data} |  cut -d '|' -f3)
      # ids=$(echo ${message_text[$id]} | awk '{print $1}' | sed -e 's/[^a-z0-9 -]//ig')
      #   idc=$(echo ${message_text[$id]} | awk '{print $3}' | sed -e 's/[^a-z0-9 -]//ig')
      #   _tru=$(echo ${message_text[$id]} | awk '{print $5}')
		[[ -z $_tru ]] && _tru='false'
		[[ -z ${idc} ]] && idc='30'
        valid=$(date '+%C%y-%m-%d' -d " +$idc days")
	  [[ $(cat ${CID}|grep "$ids" ) = "" ]] && {
	  [[ ${idc} > 366 ]] && idc='30'
		[[ -e $HOME/RegBOT/banID ]] && sed -i "/${ids}/d" $HOME/RegBOT/banID
		[[ -e $HOME/RegBOT/U_check.txt ]] && sed -i "/${ids}/d" $HOME/RegBOT/U_check.txt
		[[ -e $HOME/RegBOT/killID.log ]] && sed -i "/${ids}/d" $HOME/RegBOT/killID.log
        echo "/${ids} | $valid | ${_tru} | ${Id-ADMIN}" >> ${CID}
        echo "/${ids} | $(date '+%C%y-%m-%d') | $(date +%R)" >> $HOME/RegBOT/${ids}.reg
          bot_retorno="==== ✉️ REGISTRO APROBADO  ✉️ ====\n"
          bot_retorno+=" 🆔 : ${ids} | ACEPTADO 🧾\n"
          bot_retorno+="▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬ \n"
          bot_retorno+=" FECHA DE REGISTRO : $(date '+%C%y-%m-%d')|$(date +%R) \n VALIDO HASTA : ${valid} | 00:00\n"
          bot_retorno+=" MEMBRESIA DUALGEN EN ${_tru}\n"
          bot_retorno+="▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬ \n"
          bot_retorno+="  ✅ ID REGISTRADO EXITOSAMENTE ✅\n"
          bot_retorno+="▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬ \n"
          bot_retorno+="     💥 Bot ADMcgh GEN de KEY 💥\n"
		  bot_retorno+="           ⚜ by @ChumoGH ⚜\n"
unset i
[[ -z ${callback_query_from_username} ]] && nUSER=${message_from_username} || nUSER=${callback_query_from_username}
[[ -z ${callback_query_from_first_name} ]] && firsnme="${message_from_first_name}" || firsnme="${callback_query_from_first_name}"
[[ -z ${callback_query_from_last_name} ]] && lastnme="${message_from_last_name}" || lastnme="${callback_query_from_last_name}"
		  bot_retor=" ✉️ ESTIMADO @${nUSER} SU REGISTRO FUE APROBADO  ✉️ \n"
		  bot_retor+="▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬ \n"
          bot_retor+=" EL ADM $(cat < /etc/ADM-db/resell) APROBO TU SOLICITUD\n"
          bot_retor+="  ☺️ GRACIAS POR CONFIAR EN NOSOTROS ☺️\n"
          bot_retor+=" FECHA DE REGISTRO : $(date '+%C%y-%m-%d')|$(date +%R) \n VALIDO HASTA : ${valid} | 00:00\n"
          bot_retor+="▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬ \n"
          bot_retor+=" SU RESELLER : ${firsnme} ${lastnm} \n"
          bot_retor+="▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬ \n"
		  bot_retor+=" 🆔 : ${ids} | 🔐 ACEPTADO 🧾\n"
		  bot_retor+="▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬ \n"
		  bot_retor+=" MEMBRESIA DUALGEN EN : ${_tru}\n"
          bot_retor+="▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬ \n"
          bot_retor+=" GENERAR Key's ChumoGH /keygen\n"
          bot_retor+=" GENERAR Key's LATAM   /kltm\n"
          bot_retor+=" DOMINIO CloudFlare /domainA /domainNS\n"
          bot_retor+=" Para MENU Digita el comando /menu\n"
          bot_retor+=" INSTALAR SCRIPT REMOTO /remote\n"
          bot_retor+="▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬ \n"
          bot_retor+=" DUDAS Y SOLUCIONES CONTACTE A SU ADM!!\n SI NO OBTIENES RESPUESTA O SOLUCION CONTACTA A @ChumoGH "
		  #bot_retor+=" RENUEVA TU ACCESO 🛒🛍️ PINCHANDO 👉<a href="$(cat < /etc/urlCT)">AQUI</a>👈 \n"
          bot_retor+=" RECUERDA MANTENER TU CAPTURA DE PAGO, PARA ALGUN RECLAMO!\n"
          bot_retor+="▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬ \n"
		  #menu_BT_ADD
      msj_fun
      #msj_add ${ids}
	  ShellBot.sendMessage 	--chat_id ${ids} \
										--text "<i>$(echo -e $bot_retor)</i>" \
										--parse_mode html 
										#--reply_markup "$(ShellBot.InlineKeyboardMarkup -b 'botao_user')"

      #upfile_src
	  call.file2 "${CID}" " Respaldo con @${nUSER} \n ID : ${nombrevalue} \n FECHA $(date '+%C%y-%m-%d')"
    } || {
          bot_retorno=" ✉️ ====NOTIFICACION==== ✉️ \n"
          bot_retorno+="▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬ \n"
          bot_retorno+=" ID ${ids} ya esta Registrado\n"
          bot_retorno+="  ❌ ID NO REGISTRADO ❌\n"
          bot_retorno+="▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬ \n"
          	bot_retorno+="     💥 Bot ADMcgh GEN de KEY 💥\n"
			bot_retorno+="           ⚜ by @ChumoGH ⚜\n"
          bot_retorno+="▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬ \n"
      msj_fun
    }
}

addREVID_reply () {
      ids=$(echo ${message_text[$id]} | awk '{print $1}' | sed -e 's/[^a-z0-9 -]//ig')
        idc=$(echo ${message_text[$id]} | awk '{print $3}' | sed -e 's/[^a-z0-9 -]//ig')
        valid=$(date '+%C%y-%m-%d' -d " +$idc days")
	  [[ $(cat ${CID}|grep "$ids" ) = "" ]] && {
		[[ -e /root/RegBOT/banID ]] && sed -i "/${ids}/d" /root/RegBOT/banID
        echo "/${ids} | $valid" >> ${CID}
        echo "/${ids} | $(date '+%C%y-%m-%d') | $(date +%R)" >> ${CID}.reg
          bot_retorno="  ✉️ REGISTRO ACEPTADO  ✉️ \n"
          bot_retorno+=" 🆔 : ${ids} | ACEPTADO 🧾\n"
          bot_retorno+="▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬ \n"
          bot_retorno+=" FECHA DE REGISTRO : $(date '+%C%y-%m-%d')|$(date +%R) \n VALIDO HASTA : ${valid}|$(date +%R)\n"
          bot_retorno+="▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬ \n"
          bot_retorno+="  ✅ ID REGISTRADO EXITOSAMENTE ✅\n"
          bot_retorno+="▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬ \n"
          	bot_retorno+="     💥 Bot ADMcgh GEN de KEY 💥\n"
			bot_retorno+="           ⚜ by @ChumoGH ⚜\n"
unset i
for i in $(cat /etc/ADM-db/User-ID | awk '{print $3}'); do 
[[ "$(date -d $(date '+%C%y-%m-%d') +%s)" -ge "$(date -d $i +%s)" ]] && {
for id in $(cat /etc/ADM-db/User-ID | grep "$i" | awk '{print $1}' | sed -e 's/[^a-z0-9 -]//ig'); do
sed -i "/${id}/d" /etc/ADM-db/User-ID
          bot_retor="  🎊 𝙱𝚒𝚎𝚗𝚟𝚎𝚗𝚒𝚍𝚘  Nuevamente 𝚊𝚕  𝙱𝚘𝚝𝙶𝚎𝚗  𝙲𝚑𝚞𝚖𝚘𝙶𝙷-𝙰𝙳𝙼  🎊\n"
          bot_retor+=" SU MEMBRESIA HA FINALIZADO POR CHECK ID\n"
          bot_retor+=" FIN DE CONTRADO : $(date '+%C%y-%m-%d') - $(date +%R) \n"
          bot_retor+=" SI DESEAS APELAR TU CONTRADO, CONTACTA CON $(cat < /etc/ADM-db/resell)\n"
          bot_retor+="▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬ \n"
          bot_retor+=" ADQUIERE TU MEMBRESIA DESDE @$(ShellBot.username) , DIGITANDO /prices \n"
          bot_retor+=" RECUERDA MANTENER TU CAPTURA DE PAGO, PARA ALGUN RECLAMO!\n"
          bot_retor+="▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬ \n"
msj_add ${id}
done
}
done
[[ -z ${callback_query_from_username} ]] && nUSER=${message_from_username} || nUSER=${callback_query_from_username}
[[ -z ${callback_query_from_first_name} ]] && firsnme="${message_from_first_name}" || firsnme="${callback_query_from_first_name}"
[[ -z ${callback_query_from_last_name} ]] && lastnme="${message_from_last_name}" || lastnme="${callback_query_from_last_name}"
		  bot_retor=" ✉️ ESTIMADO @${nUSER} SU REGISTRO FUE APROBADO  ✉️ \n"
		  bot_retor+="▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬ \n"
          bot_retor+=" EL ADM $(cat < /etc/ADM-db/resell) APROBO TU SOLICITUD\n"
          bot_retor+="  ☺️GRACIAS POR CONFIAR EN NOSOTROS ☺️\n"
          bot_retor+=" FECHA DE REGISTRO : $(date '+%C%y-%m-%d')|$(date +%R) \n VALIDO HASTA : ${valid}|$(date +%R)\n"
		  bot_retor+=" 🆔 : ${ids} | 🔐 ACEPTADO 🧾\n"
		  bot_retor+=" SU RESELLER : ${firsnme} ${lastnm} \n"
          bot_retor+="▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬ \n"
          bot_retor+=" GENERAR Key's usar el comando /keygen\n"
          bot_retor+=" Para MENU Digita el comando /menu\n"
          bot_retor+="▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬ \n"
          bot_retor+=" CONTACTA ESCRIBE AL ADM $(cat < /etc/ADM-db/resell)\n SI NO OBTIENES RESPUESTA O SOLUCION CONTACTA A @ChumoGH "
          bot_retor+=" ADQUIERE TU MEMBRESIA DESDE @$(ShellBot.username) , DIGITANDO /prices \n"
          bot_retor+=" RECUERDA MANTENER TU CAPTURA DE PAGO, PARA ALGUN RECLAMO!\n"
          bot_retor+="▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬ \n"
      msj_fun
      msj_add ${ids}
      #upfile_src
	  call.file2 "${CID}" " Respaldo con @${nUSER} \n ID : ${nombrevalue} \n FECHA $(date '+%C%y-%m-%d')"
    } || {
          bot_retorno=" ✉️ ====NOTIFICACION==== ✉️ \n"
          bot_retorno+="▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬ \n"
          bot_retorno+="Este ID ya esta Registrado\n"
          bot_retorno+="  ❌ ID NO REGISTRADO ❌\n"
          bot_retorno+="▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬ \n"
          	bot_retorno+="     💥 Bot ADMcgh GEN de KEY 💥\n"
			bot_retorno+="           ⚜ by @ChumoGH ⚜\n"
          bot_retorno+="▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬ \n"
      msj_fun
    }
}

addID_reventa () {
bot_retorno=" -----🫥 FUNCION EN ESTADO BETA 🫥 ------\n"
bot_retorno+=" ▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬ \n"
bot_retorno+=" ID ${ids} VALIDO HASTA $(cat /etc/ADM-db/User-ID | grep ${ids} | awk '{print $3}')\n"
bot_retorno+=" ❌ NO REGISTRAR DUPLICADOS ❌\n"
bot_retorno+=" SE PRESENTAN REGLAS DE ESTE FORMATO \n"
bot_retorno+=" 1 ID - Podra autorizar maximo 10 IDs  \n"
bot_retorno+="  Por maximo de 6 meses de tiempo! \n"
bot_retorno+="▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬ \n"
bot_retorno+="  EL ADMIN PRINCIPAL, PODRA CONTROLAR  \n"
bot_retorno+="         ESTAS AUTORIZACIONES  \n"
bot_retorno+="▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬ \n"
	bot_retorno+="     💥 Bot ADMcgh GEN de KEY 💥\n"
	bot_retorno+="           ⚜ by @ChumoGH ⚜\n"
bot_retorno+="▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬ \n"
msj_fun
}


addID_REV () {
      ids=$(echo ${message_text[$id]} | awk '{print $1}' | sed -e 's/[^a-z0-9 -]//ig')
      #idc=$(echo ${message_text[$id]} | awk '{print $3}' | sed -e 's/[^a-z0-9 -]//ig')
      idc=$(echo ${message_text[$id]} | awk '{print $3}' | sed -e 's/[^a-z0-9 -]//ig')
	  [[ ${idc} > 180 ]] && idc='180'
      valid=$(date '+%C%y-%m-%d' -d " +$idc days")
	  [[ $(cat ${${CIDRESS}}|grep "$ids" ) = "" ]] && {
        echo "/${ids} | $valid | $(cat < ${CIDdir}/Admin-ID)" >> ${CIDRESS}
          bot_retorno="  🎊 𝙱𝚒𝚎𝚗𝚟𝚎𝚗𝚒𝚍𝚘  @${callback_query_from_username}  𝚊𝚕  𝙱𝚘𝚝𝙶𝚎𝚗  𝙲𝚑𝚞𝚖𝚘𝙶𝙷-𝙰𝙳𝙼  🎊\n"
          bot_retorno+="▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬ \n"
          bot_retorno+=" New ID: ${ids}\n"
		  bot_retorno+=" FECHA DE REGISTRO : $(date '+%C%y-%m-%d')|$(date +%R) \n VALIDO HASTA : ${valid}|$(date +%R)\n"
          bot_retorno+=" ▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬ \n"
          bot_retorno+="  ✅ ID REGISTRADO ✅\n"
          bot_retorno+="▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬ \n"
          	bot_retorno+="     💥 Bot ADMcgh GEN de KEY 💥\n"
			bot_retorno+="           ⚜ by @ChumoGH ⚜\n"
unset i
for i in $(cat ${CIDRESS} | awk '{print $3}'); do 
[[ $(date -d $i +%s) -ge $(date -d $(date '+%C%y-%m-%d') +%s) ]] || {
idlog=$(cat ${CIDRESS} | grep "$i" | awk '{print $1}' | sed -e 's/[^a-z0-9 -]//ig')
sed -i "/${idlog}/d" ${CIDRESS}
          bot_retor="  🎊 𝙱𝚒𝚎𝚗𝚟𝚎𝚗𝚒𝚍𝚘  Nuevamente 𝚊𝚕  𝙱𝚘𝚝𝙶𝚎𝚗  𝙲𝚑𝚞𝚖𝚘𝙶𝙷-𝙰𝙳𝙼  🎊\n"
          bot_retor+="Desafortunadamente tu Membresia ha Finalizado\n"
          bot_retor+="Fecha de Corte : $i \n"
          bot_retor+="Si tienes Dudas, Contacta con $(cat < /etc/ADM-db/resell)\n"
          bot_retor+="▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬ \n"
          bot_retor+="Recuerda adquirir creditos, o Realizar una Colaboracion\n $(cat < /etc/mpayu) \n"
          bot_retor+="Para mantener tu acceso al BotGen Recuerda Mostrar tu Token de Donacion o Compra\n"
          bot_retor+="▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬ \n"
msj_add ${idlog}
}
done
          bot_retor=" ✉️ Bienvenido al BotGen ADMcgh/Plus  ✉️ \n"
          bot_retor+="𝙃𝙤𝙡𝙖 『 ${callback_query_from_first_name} ${callback_query_from_last_name} 』\n"
          bot_retor+=" EL ADM $(cat < /etc/ADM-db/resell) te autorizo\n"
          bot_retor+=" AUTORIZACION EXTENDIDA HASTA EL ${valid}\n"
          bot_retor+=" GENERAR Key's usar el comando /keygen\n"
          bot_retor+=" Para MENU Digita el comando /menu\n"
          bot_retor+="▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬ \n"
          bot_retor+=" CONTACTA ESCRIBE AL ADM $(cat < /etc/ADM-db/resell)\n SI NO OBTIENES RESPUESTA O SOLUCION CONTACTA A @ChumoGH "
          bot_retor+=" ADQUIERE TU MEMBRESIA DESDE @$(ShellBot.username) , DIGITANDO /prices \n"
          bot_retor+=" RECUERDA MANTENER TU CAPTURA DE PAGO, PARA ALGUN RECLAMO!\n"
          bot_retor+="▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬ \n"
      msj_fun
      msj_add ${ids}
      #upfile_src
	  call.file2 "${CID}" " Respaldo con @${nUSER} \n ID : ${nombrevalue} \n FECHA $(date '+%C%y-%m-%d')"
    } || {
          bot_retorno=" -----🫥 ID YA REGISTRADO 🫥 ------\n"
          bot_retorno+=" ▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬ \n"
          bot_retorno+=" ID ${ids} VALIDO HASTA $(cat /etc/ADM-db/User-ID | grep ${ids} | awk '{print $3}')\n"
          bot_retorno+=" ❌ NO REGISTRAR DUPLICADOS ❌\n"
          bot_retorno+="▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬ \n"
          	bot_retorno+="     💥 Bot ADMcgh GEN de KEY 💥\n"
			bot_retorno+="           ⚜ by @ChumoGH ⚜\n"
          bot_retorno+="▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬ \n"
      msj_fun
    }
}
